version: "3.0"
services:
  rest-inmemory:
    image: hakankaan/go-rest-inmemory
    ports:
      - "8080:8080"
    restart: on-failure
  nginx:
    image: hakankaan/nginx-simple
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - "rest-inmemory"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml

    
