version: "3.0"
services:
  rest-inmemory:
    image: hakankaan/go-rest-inmemory
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml

