version: "3.0"
services:
  rest-inmemory:
    image: hakankaan/go-rest-inmemory
    ports:
      - "8080:8080"
    networks:
      - mynet
    deploy:
      restart_policy:
        condition: on-failure


networks:
  mynet:
    driver: bridge