version: "3.8"
services:
  rest-inmemory:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynet
    deploy:
      restart_policy:
        condition: on-failure


networks:
  mynet:
    driver: bridge